services:
  # Database Services
  post_database:
    image: postgres:14
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: post
    volumes:
      - postdb_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    
  reserve_database:
    image: postgres:14
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: reserve
    volumes:
      - reservedb_data:/var/lib/postgresql/data
    ports:
      - "5438:5432"

  notification_database:
    image: postgres:14
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: notification
    volumes:
      - notificationdb_data:/var/lib/postgresql/data
    ports:
      - "5436:5432"

  user_database:
    image: postgres:14
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: user
    volumes:
      - userdb_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  activity_database:
    image: mongo:6
    container_name: mongo_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: activity-log
      MONGO_INITDB_USERNAME: user
      MONGO_INITDB_PASSWORD: user
    volumes:
      - activity_mongo_data:/data/db
    ports:
      - "27017:27017"

  # Application Services
  post_service:
    image: post
    command: go run ./cmd/main.go
    depends_on:
      - post_database
    ports:
      - "8081:8081"
      - "30043:30043"
    volumes:
      - ./config/config-deployment-post.yaml:/app/config/config.yaml

  reserve_service:
    image: reserve
    command: go run ./cmd/main.go
    depends_on:
      - reserve_database
    ports:
      - "8082:8082"
    volumes:
      - ./config/config-deployment-reserve.yaml:/app/config/config.yaml

  notification_service:
    image: notification
    command: go run ./cmd/main.go
    depends_on:
      - notification_database
    ports:
      - "8084:8084"
    volumes:
      - ./config/config-deployment-notification.yaml:/app/config/config.yaml

  auth_service:
    image: user
    command: go run ./cmd/main.go
    depends_on:
      - user_database
    ports:
      - "8083:8083"
    volumes:
      - ./config/config-deployment-auth.yaml:/app/config/config.yaml
  activity_service:
    image: activity
    command: go run ./cmd/main.go
    depends_on:
      - activity_database
    ports:
      - "8085:8085"
    volumes:
      - ./config/config-deployment-activity.yaml:/app/config/config.yaml

volumes:
  postdb_data:
  activity_mongo_data:
  reservedb_data:
  notificationdb_data:
  userdb_data: